#include "game_app.h"

/*
    This file is used to contain some templates for SUOKDU
    This contains finished SUDOKUs from the web
    It is only temporary solution, later in development templates are going to be generated by algorythm

    Structure of those templates should be:
        1) Array of array of ints
        2) Array of ints
        3) Identical structures as SUDOKU
        4) ?
    

*/

//structure visualation
/*

     BIGsqr   |   BIGsqr   |  BIGsqr  
   [smallsqr] | [smallsqr] | [smallsqr]
  --------------------------------------
     BIGsqr   |   BIGsqr   |   BIGsqr  
   [smallsqr] | [smallsqr] | [smallsqr]
  --------------------------------------
     BIGsqr   |   BIGsqr   |   BIGsqr  
   [smallsqr] | [smallsqr] | [smallsqr]

*/

void template_assigment(SUDOKU *SUDOKU_template, int template_num);
void template_creation();