#include <stdlib.h>
#include <stdio.h>
#include "SUDOKU_template.h"
#include "game_app.h"

/*
    This file is used to contain some templates for SUOKDU
    This contains finished SUDOKUs from the web
    It is only temporary solution, later in development templates are going to be generated by algorythm

    Structure of those templates should be:
        1) Array of array of ints
        2) Array of ints
        3) Identical structures as SUDOKU <-
        4) ?
    

*/

//structure visualation

/*

     BIGsqr   |   BIGsqr   |  BIGsqr  
   [smallsqr] | [smallsqr] | [smallsqr]
  --------------------------------------
     BIGsqr   |   BIGsqr   |   BIGsqr  
   [smallsqr] | [smallsqr] | [smallsqr]
  --------------------------------------
     BIGsqr   |   BIGsqr   |   BIGsqr  
   [smallsqr] | [smallsqr] | [smallsqr]

*/

SMALLsqr* template1_content[3][3];

//definition of contents for templates

void template_creation()
{
    template1_content[0][0]->int data={ 
                                    {5, 3, 4}, 
                                    {6, 7, 2}, 
                                    {1, 9, 8}
                                   };
    template1_content[0][1]->data[3][3] = {6, 7, 8, 1, 9, 5, 3, 4, 2};
    template1_content[0][2]->data[3][3] = {9, 1, 2, 3, 4, 8, 5, 6, 7};
}

void template_assigment(SUDOKU *SUDOKU_template, int template_num)
{
     SMALLsqr* template_temp[3][3];

     &template_temp = &template1_content;

    //this should be done in loop to go int by int as it is not possible to pass array to arrray

    SUDOKU_template->GRID[0][0].content.data[0][0]=template1_content[0][0]->data[0][0];

}